name: Update Badges

on:
  push:
    branches: [master, main]
  schedule:
    - cron: "0 0 * * 0" # Toda semana

jobs:
  update-badges:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate coverage badge
        run: |
          npm ci
          npm test -- --coverage --passWithNoTests
          npx coverage-badges

      - name: Commit badge
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update coverage badges"
          git push
