name: CI/CD Pipeline

on:
  push:
    branches: [main, master, develop, remote]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # Permite executar manualmente

permissions:
  contents: read
  pull-requests: write
  checks: write
  statuses: write

jobs:
  # Job de validação rápida
  quick-checks:
    name: Quick Validation
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Validate package.json
        run: npm run lint:check || true

      - name: Check for security vulnerabilities
        run: npm audit --audit-level=moderate || true

  # Lint e formatação
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    needs: quick-checks

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: "npm"

      - run: npm ci

      - name: ESLint
        run: npm run lint:check

      - name: Prettier
        run: npm run format:check

      - name: TypeScript
        run: npx tsc --noEmit

  # Testes unitários
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: quick-checks

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: "npm"

      - run: npm ci

      - name: Run tests with coverage
        run: npm test -- --coverage --passWithNoTests

      - name: Upload coverage
        if: matrix.node-version == 20
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true

  # Build
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: "npm"

      - run: npm ci

      - name: Build
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: build-${{ github.sha }}
          path: dist/
          retention-days: 7

  # Testes E2E com Playwright
  e2e-tests:
    name: E2E Tests (Playwright)
    runs-on: ubuntu-latest
    needs: quick-checks

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test:e2e:chromium
        continue-on-error: true

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-results
          path: test-results/
          retention-days: 30

  # Job de sucesso (para branch protection)
  ci-success:
    name: CI Success
    runs-on: ubuntu-latest
    needs: [lint, test, build, e2e-tests]
    if: always()

    steps:
      - name: Check all jobs
        run: |
          if [ "${{ needs.lint.result }}" != "success" ] || \
             [ "${{ needs.test.result }}" != "success" ] || \
             [ "${{ needs.build.result }}" != "success" ] || \
             [ "${{ needs.e2e-tests.result }}" != "success" ]; then
            echo "❌ CI failed!"
            exit 1
          fi
          echo "✅ All CI checks passed!"
